name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-20.04"

jobs:
  - job: run_test
    strategy:
      matrix:
        Python3_9:
          python.version: "3.9"
        Python3_10:
         python.version: "3.10"
        Python3_11:
         python.version: "3.11"

    timeoutInMinutes: 10

    steps:
      - task: UsePythonVersion@0
        displayName: Set python version
        inputs:
          versionSpec: "$(python.version)"
      - script: |
          set -exv  # Echo commands before they are run
          export APKTOOL_VERSION=2.9.3
          export DEX2JAR_VERSION=2.4
          export AAPT2_VERSION=8.2.2-10154469
          sudo apt-get update
          sudo apt-get install -yy build-essential libffi-dev libfuzzy-dev python3-dev libimage-exiftool-perl openjdk-8-jre-headless java-common libc6-i386 lib32z1 lib32gcc1 unzip wget
          sudo mkdir -p /usr/share/man/man1
          sudo chmod +x $(pwd)/setup_support.sh && $(pwd)/setup_support.sh
          sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir assemblyline assemblyline_v4_service
          [ -f $(pwd)/requirements.txt ] && sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir -r $(pwd)/requirements.txt
          [ -f $(pwd)/tests/requirements.txt ] && sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir -r $(pwd)/tests/requirements.txt
          sudo rm -rf /tmp/* /var/lib/apt/lists/* ~/.cache/pip
        displayName: Setup environment
      - script: python -m pytest -p no:cacheprovider --durations=10 -rsx -vv --disable-warnings
        displayName: Test
