name: tests

variables:
  - group: unittest-samples

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-20.04"

resources:
  repositories:
    - repository: PipelineTemplates
      type: github
      name: CybercentreCanada/assemblyline-pipeline-templates
      ref: refs/heads/main
      endpoint: github-repo-sa
      trigger: none
    - repository: unittest-samples
      type: github
      name: $(unittest_samples_repository)
      ref: main
      endpoint: github-repo-sa
      trigger: none

extends:
  template: stages/test-service.yaml@PipelineTemplates
  parameters:
    python_versions:
      - "3.9"
      - "3.10"
      - "3.11"
    samples_repo: unittest-samples
    test_container: "false"
    test_env:
      APKTOOL_VERSION: "2.9.3"
      DEX2JAR_VERSION: "2.4"
      AAPT2_VERSION: "8.2.2-10154469"
