name: build

trigger:
  tags:
    include: ["v*"]
pr: none

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: deploy
  jobs:
  - job: deploy
    displayName: Deploy containers to dockerhub
    variables:
      - group: deployment-information
    steps:
    - task: Docker@2
      displayName: Login to docker hub
      inputs:
        command: login
        containerRegistry: dockerhub
    - script: |
        set -xv  # Echo commands before they are run
        export TAG=${BUILD_SOURCEBRANCH#"refs/tags/v"}
        docker build --build-arg version=$TAG -t cccs/assemblyline-service-apkaye:$TAG -t cccs/assemblyline-service-apkaye:latest .
        displayName: Build containers
    - script: |
        docker run -v `pwd`/test/:/opt/al_service/test/ cccs/assemblyline-service-apkaye:latest bash -c 'pip install -U -r test/requirements.txt; pytest'
      displayName: Test containers
    - script: |
        docker push cccs/assemblyline-service-apkaye
      displayName: Deploy to Docker Hub
